# Generated by Django 4.2.3 on 2023-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="initial_debt",
        ),
        migrations.AddField(
            model_name="creditcard",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Credit Card Debt",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=50, verbose_name="Account Name"),
        ),
    ]
