# Generated by Django 4.2.3 on 2023-09-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Employee", "Employee"),
                    ("Business", "Business"),
                    ("Student", "Student"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
