# Generated by Django 4.2.3 on 2023-11-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0002_remove_creditcard_initial_debt_creditcard_debt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="creditcard",
            options={
                "verbose_name": "Credit Card",
                "verbose_name_plural": "Credit Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="investmentaccount",
            options={
                "verbose_name": "Investment Account",
                "verbose_name_plural": "Investment Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="loanaccount",
            options={
                "verbose_name": "Loan Account",
                "verbose_name_plural": "Loan Accounts",
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=50),
        ),
    ]
