# Generated by Django 4.2.3 on 2023-10-13 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0002_userprofile_profession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="dob",
            new_name="dateOfBirth",
        ),
    ]
