# Generated by Django 4.2.3 on 2023-09-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("OTHER", "Prefer not to say"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="symbol",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
