# Generated by Django 4.2.3 on 2023-09-16 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "chittabook",
            "0003_alter_userprofile_currency_alter_userprofile_gender_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="symbol",
        ),
    ]
