# Generated by Django 4.2.5 on 2023-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0003_alter_account_options_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investmentaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='debt',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
