# Generated by Django 4.2.3 on 2023-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0003_rename_dob_userprofile_dateofbirth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="dateOfBirth",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
    ]
