# Generated by Django 4.2.5 on 2023-11-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0004_alter_account_options_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category', 'sub_category'], 'verbose_name_plural': 'Categories'},
        ),
    ]
