# Generated by Django 4.2.3 on 2023-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0004_remove_userprofile_dateofbirth_userprofile_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="numeric",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
