# Generated by Django 4.2.5 on 2023-10-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0009_savingsaccount_loanaccount_investmentaccount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingsAccount',
            new_name='BankAccount',
        ),
        migrations.RenameModel(
            old_name='CreditCardAccount',
            new_name='CreditCards',
        ),
        migrations.DeleteModel(
            name='CheckingAccount',
        ),
    ]
