# Generated by Django 4.2.3 on 2023-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0013_expensecategory_expense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.AddField(
            model_name="expense",
            name="note",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="account",
            field=models.CharField(max_length=256),
        ),
    ]
