# Generated by Django 4.2.5 on 2023-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0018_alter_expense_user_alter_expensecategory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='current_value',
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Current Value'),
        ),
    ]
