# Generated by Django 4.2.5 on 2023-10-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0020_expense_subcategory_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=256),
        ),
    ]
