# Generated by Django 4.2.5 on 2023-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0022_remove_expense_subcategory_alter_expense_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.CharField(max_length=256),
        ),
    ]
