# Generated by Django 4.2.5 on 2023-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chittabook', '0023_alter_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
