# Generated by Django 4.2.3 on 2023-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chittabook", "0024_expense_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcards",
            name="card_name",
        ),
        migrations.RemoveField(
            model_name="loanaccount",
            name="lender_name",
        ),
        migrations.AddField(
            model_name="creditcards",
            name="account_name",
            field=models.CharField(max_length=100, null=True, verbose_name="Card Name"),
        ),
        migrations.AddField(
            model_name="income",
            name="subcategory",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="account_name",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Lender Name"
            ),
        ),
    ]
