name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        pip3 install django-allauth
        pip3 install crispy-bootstrap5
        pip3 install certifi
        python3 manage.py test
